---

- name: Create directories owned by user deploy
  file: dest={{ item }} owner=deploy group=deploy state=directory
  with_items:
    - "{{ logs_path }}/strassengezwitscher_dev"
    - "{{ logs_path }}/strassengezwitscher_master"
