---

- name: Deploy django develop branch to server
  hosts: strassengezwitscher
  remote_user: deploy

  roles:
    - { role: strassengezwitscher, dir: 'strassengezwitscher_dev', branch: 'develop', secret_key: '{{ django_develop_secret_key }}' }
