---

- name: Deploy django master branch to server
  hosts: strassengezwitscher
  remote_user: deploy

  roles:
    - { role: strassengezwitscher, dir: 'strassengezwitscher_master', branch: 'master', secret_key: '{{ django_master_secret_key }}' }
