- name: Install required packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 604800
  become: yes
  with_items:
    - git

- name: Install gulp and npm-prune via npm
  npm:
    name: '{{ item }}'
    production: yes
    global: yes
  become: yes
  with_items:
    - gulp
    - prune

- name: Install uwsgi configs
  template:
    src: uwsgi.site.j2
    dest: '{{ uwsgi_path }}/{{ item }}.ini'
  become: yes
  with_items:
    - strassengezwitscher_dev
    - strassengezwitscher_master
  notify: restart uwsgi

- name: Install uwsgi emperor config
  template:
    src: emperor.ini.j2
    dest: /etc/uwsgi/emperor.ini
  become: yes
  notify: restart uwsgi

- name: Check if uwsgi log files exist
  stat: path={{ logs_path }}/{{ item }}
  with_items:
    - "{{ uwsgi_emperor_log_name }}"
  register: logs_exist

- name: Create uwsgi log files
  file:
    path: '{{ logs_path }}/{{ item.item }}'
    state: touch
    owner: deploy
    group: deploy
  become: yes
  when: not item.stat.exists
  with_items: '{{ logs_exist.results }}'

- name: Install uwsgi systemd service
  copy:
    src: emperor.uwsgi.service
    dest: /etc/systemd/system/emperor.uwsgi.service
  become: yes

- name: Enable autostarting uwsgi
  service: # TODO: use systemd with daemon_reload instead (supported in ansible 2.2)
    name: emperor.uwsgi
    enabled: yes
  become: yes

- name: Install uwsgi reload scripts
  template:
    src: reload.sh.j2
    dest: '/root/reload_{{ item }}.sh'
    mode: 0754
  become: yes
  with_items:
    - strassengezwitscher_dev
    - strassengezwitscher_master

- name: Install htpasswd
  htpasswd:
    name: admin
    path: '{{ admin_htpasswd }}'
    password: '{{ admin_password }}'
  become: yes
  notify: reload nginx

- name: Install https nginx configs
  template:
    src: nginx_tls.site.j2
    dest: '/etc/nginx/sites-available/{{ item.branch }}'
  become: yes
  with_items:
    - { branch: 'strassengezwitscher_dev',
        server_name: '{{ dev_server_names }}',
        dir: 'dev.streetcoverage.org',
        htaccess: True }
    - { branch: 'strassengezwitscher_master',
        server_name: '{{ master_server_names }}',
        dir: 'streetcoverage.org',
        wordpress: True }
  notify: reload nginx

- name: Enable nginx configs
  file:
    src: '/etc/nginx/sites-available/{{ item }}'
    dest: '/etc/nginx/sites-enabled/{{ item }}'
    state: link
  become: yes
  with_items:
    - strassengezwitscher_dev
    - strassengezwitscher_master
  notify: reload nginx

- name: Install deployment scripts
  template:
    src: deploy.sh.j2
    dest: '/home/deploy/{{ item.script_name }}.sh'
    mode: 0754
  with_items:
    - { dir: 'strassengezwitscher_dev',
        script_name: 'deploy_develop' }
    - { dir: 'strassengezwitscher_master',
        script_name: 'deploy_master' }

- name: allow travis to run deployment scripts
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "travis ALL=(deploy) NOPASSWD: /home/deploy/deploy_{{ item }}.sh"
  become: yes
  with_items:
    - master
    - develop

- name: include wordpress configuration for shop
  include: wordpress.yml
  become: yes
  tags:
    - wordpress
  notify: reload nginx
