---

- name: Fetch repository
  git: accept_hostkey=yes force=yes repo=git@github.com:Strassengezwitscher/Strassengezwitscher.git dest={{ project_path }}/{{ dir }}/ version={{ branch }}
  notify: restart uwsgi

# - name: Install production specific django settings
#   template: src=localsettings.py.j2 dest={{ project_path }}/{{ dir }}/strassengezwitscher/strassengezwitscher/localsettings.py

- name: Install dependencies using npm
  npm: path={{ project_path }}/{{ dir }} production=yes global=no

- name: Run gulp
  command: node_modules/gulp/bin/gulp.js dist --production
  args:
    chdir: '{{ project_path }}/{{ dir }}/'
    removes: '{{ project_path }}/{{ dir }}/gulpfile.js' # run only if gulpfile.js exists (it is not removed)

- name: Install python packages
  pip: requirements={{ project_path }}/{{ dir }}/requirements.txt virtualenv={{ project_path }}/{{ dir }}/venv

- name: Collect django staticfiles
  django_manage: app_path={{ project_path }}/{{ dir }}/{{ project_name }}/ command=collectstatic virtualenv={{ project_path }}/{{ dir }}/venv

- name: Migrate django databases
  django_manage: app_path={{ project_path }}/{{ dir }}/{{ project_name }}/ command=migrate virtualenv={{ project_path }}/{{ dir }}/venv
