---

ansible_become_pass:                                < set me in vault >
admin_password:                                     < set me in vault >
django_master_secret_key:                           < set me in vault >
django_develop_secret_key:                          < set me in vault >
django_admins:                                      < set me in vault >
django_default_from_email:                          < set me in vault >
django_email_from_contact:                          < set me in vault >
django_master_email_to_contact_confidential:        < set me in vault >
django_develop_email_to_contact_confidential:       < set me in vault >
django_master_email_to_contact_non_confidential:    < set me in vault >
django_develop_email_to_contact_non_confidential:   < set me in vault >
django_email_host:                                  < set me in vault >
django_email_host_user:                             < set me in vault >
django_email_host_password:                         < set me in vault >
django_grecaptcha_key:                              < set me in vault >
django_twitter_consumer_key:                        < set me in vault >
django_twitter_consumer_secret:                     < set me in vault >
django_twitter_access_token:                        < set me in vault >
django_twitter_access_secret:                       < set me in vault >
angular_grecaptcha_key:                             < set me in vault >

project_name: crowdgezwitscher
admin_htpasswd: /etc/nginx/htpasswd_strassengezwitscher_dev_admin
uwsgi_path: /etc/uwsgi/vassals
uwsgi_site_app_log_name: app.log
uwsgi_site_req_log_name: requests.log
uwsgi_emperor_log_name: uwsgi-emperor.log
logs_path: /var/log
project_path: /home/deploy
sockets_path: /run/uwsgi
pids_path: /run/uwsgi
letsencrypt_webroot: /var/www/letsencrypt

# The domain names are hardcoded in roles/tls_certificates/tasks/main.yml again for getting TLS certificates.
# If you change something here you might want to apply your changes there, too.
master_server_names: crowdgezwitscher.de www.crowdgezwitscher.de streetcoverage.org www.streetcoverage.org strassengezwitscher.de www.strassengezwitscher.de
dev_server_names: dev.streetcoverage.org

# config for additional wp for merch shop
# no custom template and config included at this point
wordpress_installs:
      - name: wordpress
        dbname: {{ vault_wordpress_installs.dbname }}
        dbuser: {{ vault_wordpress_installs.dbuser }}
        dbpass: {{ vault_wordpress_installs.dbpass }}
        dbhost: localhost
        path: /var/www/wordpress
        url: http://shop.strassengezwitscher.de
        title: Straßengezwitscher Shop
        admin_name: {{ vault_wordpress_installs.admin_name }}
        admin_email: {{ vault_wordpress_installs.admin_email }}
        admin_password: {{ vault_wordpress_installs.admin_password }}
        themes:
          - name: twentyseventeen
            activate: true
          - name: twentythirteen
        plugins:
          - name: woocommerce
            activate: false
        users: {}
        options: []
        queries: []

