---

- name: Install uwsgi via pip
  pip: name={{ item }}
  become: yes
  with_items:
    - uwsgi
    - uwsgitop

- name: Create sites directories
  file: path={{ item }} state=directory
  become: yes
  with_items:
    - "{{ uwsgi_path }}"
