---

- name: Install uwsgi via apt
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 604800
  become: yes
  with_items:
    - uwsgi-core
    - uwsgi-plugin-python3

- name: Install helper tool uwsgitop via pip
  pip: name=uwsgitop
  become: yes

- name: Create sites directories
  file: path={{ item }} state=directory
  become: yes
  with_items:
    - "{{ uwsgi_path }}"
