- name: Install http-only nginx config(s)
  template:
    src: nginx_no_tls.site.j2
    dest: '/etc/nginx/sites-available/{{ item.branch }}'
    force: no
  with_items:
    - { branch: 'strassengezwitscher_dev',
        server_name: '{{ dev_server_names }}',
        htaccess: True }
    - { branch: 'strassengezwitscher_master',
        server_name: '{{ master_server_names }}'}
    - { branch: '{{ wordpress_installs[0].name  }}',
        server_name: '{{ wordpress_installs[0].url.split("//")[1] }}'}

- name: Enable nginx configs
  file:
    src: '/etc/nginx/sites-available/{{ item }}'
    dest: '/etc/nginx/sites-enabled/{{ item }}'
    state: link
  with_items:
    - strassengezwitscher_dev
    - strassengezwitscher_master
    - '{{ master_server_names }}'
  notify: reload nginx

- name: Start nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: Get TLS certificates
  command: letsencrypt certonly --webroot -w {{ letsencrypt_webroot}} {{ item }} --non-interactive
  with_items:
    - "-d streetcoverage.org -d www.streetcoverage.org -d strassengezwitscher.de -d www.strassengezwitscher.de -d crowdgezwitscher.de -d www.crowdgezwitscher.de"
    - "-d dev.streetcoverage.org"
    - "-d mattermost.streetcoverage.org"
    - "-d shop.strassengezwitscher.de"

- name: create PATH for cron
  cron:
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: Use cron to renew TLS certificates
  cron:
    name: "Renew TLS certificates"
    hour: 4
    minute: 10
    weekday: 0
    job: "letsencrypt renew --non-interactive > /dev/null 2>&1 && nginx -t > /dev/null 2>&1 && service nginx restart"
