- name: Install http-only nginx config(s)
  template: src=nginx_no_tls.site.j2 dest=/etc/nginx/sites-available/{{ item.branch }}
  become: yes
  with_items:
    - { branch: 'strassengezwitscher_dev', server_name: '{{ dev_server_names }}', dir: 'dev.streetcoverage.org', htaccess: True }
    - { branch: 'strassengezwitscher_master', server_name: '{{ master_server_names }}', dir: 'streetcoverage.org' }

- name: Enable nginx configs
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  become: yes
  with_items:
    - strassengezwitscher_dev
    - strassengezwitscher_master
  notify: reload nginx

- name: Start nginx
  service: name=nginx enabled=yes state=started
  become: yes

- name: Get TLS certificates
  command: letsencrypt certonly --webroot -w {{ letsencrypt_webroot}} {{ item }} --non-interactive
  become: yes
  with_items:
    - "-d streetcoverage.org -d www.streetcoverage.org -d strassengezwitscher.de -d www.strassengezwitscher.de"
    - "-d dev.streetcoverage.org"